name: pack
description: .NET build action

runs:
  using: "composite"
  steps:
    - name: Pack ${{ inputs.package }} NuGet package
      run: dotnet pack src/${{ inputs.package }}/${{ inputs.package }}.csproj -c Release
      shell: bash

    - name: Prep package
      shell: bash
      run: dotnet nuget add source --username Geneirodan --password ${{ secrets.NUGET_PACKAGE_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Geneirodan/index.json"

    - name: Push package to GitHub packages
      shell: bash
      run: dotnet nuget push src/${{ inputs.package }}/bin/Release/*.nupkg --api-key ${{ secrets.NUGET_PACKAGE_TOKEN }}  --source "github"
