name: Action to build and publish the project as a nuget package to github package registry

on:
  workflow_call:
    inputs:
      package:
        required: true
        type: string

jobs:
  pack:
    runs-on: ubuntu-latest
    
    steps:
      - name: Pack ${{ inputs.package }} NuGet package
        run: dotnet pack src/${{ inputs.package }}/${{ inputs.package }}.csproj -c Release

      - name: Upload ${{ inputs.package }} NuGet package to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: Geneirodan.Generics.${{ inputs.package }}
          path: src/${{ inputs.package }}/bin/Release/
  
  push:
    runs-on: ubuntu-latest
    needs: pack
    if: github.ref == 'refs/heads/main' # only run job if on the main branch
    
    steps:
      - name: Download ${{ inputs.package }} NuGet package artifact
        uses: actions/download-artifact@v4
        with:
          name: Geneirodan.Generics.${{ inputs.package }}
      - name: Prep package
        steps:
        run: dotnet nuget add source --username Geneirodan --password ${{ secrets.NUGET_PACKAGE_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Geneirodan/index.json"
      - name: Push package to GitHub packages
        run: dotnet nuget push Geneirodan.Generics.${{ inputs.package }}/*.nupkg --api-key ${{ secrets.NUGET_PACKAGE_TOKEN }}  --source "github"
