name: Publish

on:
  push:
    branches: [ "main", "workflows" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        
      - uses: ./.github/actions/build
        
      - uses: ./.github/actions/pack
        with:
          package: Repository
          
      - uses: ./.github/actions/pack
        with:
          package: CrudService