name: Publish

on:
  push:
    branches: [ "main", "workflows" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    outputs: 
      version: ${{ steps.gitversion.outputs.semVer }}
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/build
        with:
          configuration: Release

      - uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.x'
      
      - id: gitversion
        uses: gittools/actions/gitversion/execute@v0
  
  find-packages:
    runs-on: ubuntu-latest
    
    outputs:
      packages: ${{ steps.folders.outputs.folders }}
    steps:
      - uses: actions/checkout@v4

      - id: folders
        uses: philips-labs/list-folders-action@v1
        with:
          path: ./src
  pack:
    runs-on: ubuntu-latest
    
    needs: build
    
    strategy:
      matrix:
        package: [ find-packages ]
    
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/pack
        with:
          package: ${{ matrix.package }}
          token: ${{ secrets.NUGET_PACKAGE_TOKEN }}
          version: ${{ needs.build.outputs.version }}