name: Publish

on:
  push:
    branches: [ "main", "workflows" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    outputs: 
      version: ${{ steps.gitversion.outputs.MajorMinorPatch }}
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/build
        with:
          configuration: Release

      - uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.x'
      
      - id: gitversion
        uses: gittools/actions/gitversion/execute@v0
  
  find-packages:
    runs-on: ubuntu-latest
    
    outputs:
      packages: ${{ steps.folders.outputs.packages }}
    steps:
      - uses: actions/checkout@v4

      - id: folders
        shell: bash
        run: |
          cd ./src 
          list=$(set -- */; printf "%s\n" "${@%/}")
          packages=$(echo '[ "'"$(echo "$list" | sed ':a;N;$!ba;s/\n/", "/g')"'" ]')
          echo "packages=$packages" >> $GITHUB_OUTPUT
        
          
  pack:
    runs-on: ubuntu-latest
    
    needs: [build, find-packages]
    
    strategy:
      matrix:
        package: ${{ fromJSON(needs.find-packages.outputs.packages) }}
    
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/pack
        with:
          package: ${{ matrix.package }}
          token: ${{ secrets.NUGET_PACKAGE_TOKEN }}
          version: ${{ needs.build.outputs.version }}