name: Publish

on:
  push:
    branches: [ "main", "workflows" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        
      - uses: ./.github/actions/build
        
  pack:
    runs-on: ubuntu-latest
    
    needs: build
    
    strategy:
      matrix:
        package: ["Repository", "CrudService"]
        
    steps:
      - uses: actions/checkout@v4
        
      - uses: ./.github/actions/pack
        with:
          package: ${{ matrix.package }}
          token: ${{ secrets.NUGET_PACKAGE_TOKEN }}