name: Action to build and publish the project as a nuget package to github package registry

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/dotnet.yml
      - uses: ./.github/actions/pack.yml
        with:
          package: Repository
      - uses: ./.github/actions/pack.yml
        with:
          package: CrudService